#! /bin/csh
#

cd /run/media/mdtest/RSF0001/rsf/relampago

mkdir -p cfradial

rsync -av /scr/snow1/rsfdata/projects/relampago/cfradial/csu_moments cfradial
rsync -av /scr/snow1/rsfdata/projects/relampago/cfradial/doe cfradial

rsync -av /scr/snow1/rsfdata/projects/relampago/mdv .
rsync -av /scr/snow1/rsfdata/projects/relampago/spdb .


