#!/bin/csh

# get posn of hail drone team, using wget
# this is Josh Soderholm's group    

mkdir -p $DATA_DIR/relampago/raw/hailDronePosn
cd $DATA_DIR/relampago/raw/hailDronePosn

wget -nd -nc -c -r \
    https://www.dropbox.com/s/sgwpxm9gg3nopc2/hailteamcoords.csv |& \
    LogFilter -d $ERRORS_LOG_DIR -p getHailDronePosn &


